import Navbar from "./components/Navbar";
import "./globals.css";
export const metadata = {
  title: "apds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body>
        <div>
          <Navbar/>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
